### ISSUE TITLE
Tracking bug for missing setters

### ISSUE THREAD

**Issue by seanbright** [asterisk-java/asterisk-java#234]
- [ ] 'swapuniqueid' to 'GW1-1517402850.50086' on org.asteriskjava.manager.event.BridgeEnterEvent
- [ ] 'bridgevideosourcemode' to 'none' on org.asteriskjava.manager.event.BridgeCreateEvent
- [ ] 'accountcode' to 'False' on org.asteriskjava.manager.event.HangupEvent
- [ ] 'language' to 'en' on org.asteriskjava.manager.event.ConfbridgeJoinEvent
- [ ] 'linkedid' to '1474881412.1' on org.asteriskjava.manager.event.ConfbridgeJoinEvent
- [ ] 'language' to 'en' on org.asteriskjava.manager.event.ConfbridgeLeaveEvent
- [ ] 'linkedid' to '1475486824.3' on org.asteriskjava.manager.event.ConfbridgeLeaveEvent
- [ ] 'accountcode' to '762377' on org.asteriskjava.manager.event.HangupEvent
- [ ] 'cause' to '1' on org.asteriskjava.manager.event.HangupRequestEvent
- [ ] 'class' to 'default' on org.asteriskjava.manager.event.MusicOnHoldEvent

**Comment by scgm11** [comment]
'bridgevideosourcemode' to 'none' on org.asteriskjava.manager.event.BridgeCreateEvent
is on PR #245 missing properties and datatype

**Comment by Niemi** [comment]
Hi to all.
maybe wrong topic. but in release 2.0.2 we have waring:

> Unable to set property 'privilege' to 'SMSCommand' on org.asteriskjava.manager.response.ManagerResponse: no setter.

**Comment by gudge25** [comment]
same issue

**Comment by bsutton** [comment]
You will need to push a patch if you want this fixed.
Have a look at some of the above issues and their commits to see how its done.
Its very easy.

**Comment by Niemi** [comment]
ok. i will try.

**Comment by CaptainMegane** [comment]
I will have a look, if I can provide some patches, too :-)
